import 'package:supabase_flutter/supabase_flutter.dart' as sb;

import '../models/app_notification.dart';
import '../models/notification_preferences.dart';

/// Notifications — live against `notifications`/`notification_preferences`
/// (migration_004.md). The client CANNOT create notifications (no INSERT
/// policy; they're generated by future backend logic) — only fetch/
/// mark-read/delete. `notification_queue` must never be touched from Flutter.
///
/// No realtime yet per the doc — the feed is manually refreshed
/// (pull-to-refresh / provider invalidation), not push-updated.
abstract interface class NotificationRepository {
  Future<List<AppNotification>> notifications();
  Future<void> markAsRead(String notificationId);
  Future<void> delete(String notificationId);

  Future<NotificationPreferences> getPreferences();
  Future<void> updatePreferences(NotificationPreferences prefs);

  /// Run once, right after sign-up.
  Future<void> createDefaultPreferences();
}

class SupabaseNotificationRepository implements NotificationRepository {
  const SupabaseNotificationRepository();

  sb.SupabaseClient get _client => sb.Supabase.instance.client;

  @override
  Future<List<AppNotification>> notifications() async {
    final rows = await _client
        .from('notifications')
        .select()
        .order('created_at', ascending: false);
    return (rows as List)
        .map((n) => AppNotification.fromJson(n as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<void> markAsRead(String notificationId) => _client
      .from('notifications')
      .update({'is_read': true, 'read_at': DateTime.now().toIso8601String()})
      .eq('id', notificationId);

  @override
  Future<void> delete(String notificationId) =>
      _client.from('notifications').delete().eq('id', notificationId);

  @override
  Future<NotificationPreferences> getPreferences() async {
    final row = await _client
        .from('notification_preferences')
        .select()
        .single();
    return NotificationPreferences.fromJson(row);
  }

  @override
  Future<void> updatePreferences(NotificationPreferences prefs) {
    final myId = _client.auth.currentUser!.id;
    return _client
        .from('notification_preferences')
        .update({
          'push_enabled': prefs.pushEnabled,
          'email_enabled': prefs.emailEnabled,
          'like_notifications': prefs.likeNotifications,
          'match_notifications': prefs.matchNotifications,
          'message_notifications': prefs.messageNotifications,
          'call_notifications': prefs.callNotifications,
          'profile_view_notifications': prefs.profileViewNotifications,
          'marketing_notifications': prefs.marketingNotifications,
        })
        .eq('user_id', myId);
  }

  @override
  Future<void> createDefaultPreferences() async {
    final myId = _client.auth.currentUser!.id;
    await _client.from('notification_preferences').insert({'user_id': myId});
  }
}
