// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH5zCmGHzAqBqC9NZZRA7GTgEc_nrONOg',
    appId: '1:119566056876:web:6436f502d741d051e00e09',
    messagingSenderId: '119566056876',
    projectId: 'love-me-international',
    authDomain: 'love-me-international.firebaseapp.com',
    storageBucket: 'love-me-international.firebasestorage.app',
    measurementId: 'G-7WGH1V9QZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98GW470e4gwB8ObYEqoI8v7FQ1qCnkKM',
    appId: '1:119566056876:android:c37e2164fd3f647ae00e09',
    messagingSenderId: '119566056876',
    projectId: 'love-me-international',
    storageBucket: 'love-me-international.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbVax3UFXqpSgpMwefrq708STNqlEX4IY',
    appId: '1:119566056876:ios:660556ffe55169bbe00e09',
    messagingSenderId: '119566056876',
    projectId: 'love-me-international',
    storageBucket: 'love-me-international.firebasestorage.app',
    iosBundleId: 'com.example.loveMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbVax3UFXqpSgpMwefrq708STNqlEX4IY',
    appId: '1:119566056876:ios:660556ffe55169bbe00e09',
    messagingSenderId: '119566056876',
    projectId: 'love-me-international',
    storageBucket: 'love-me-international.firebasestorage.app',
    iosBundleId: 'com.example.loveMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH5zCmGHzAqBqC9NZZRA7GTgEc_nrONOg',
    appId: '1:119566056876:web:527bae8f40e8af2ee00e09',
    messagingSenderId: '119566056876',
    projectId: 'love-me-international',
    authDomain: 'love-me-international.firebaseapp.com',
    storageBucket: 'love-me-international.firebasestorage.app',
    measurementId: 'G-92YJRHVVWR',
  );
}
