import 'package:equatable/equatable.dart';

/// Mirrors the live `notifications` table (migration_004.md). The client
/// cannot create these — they're generated by future backend logic — so this
/// is read/update(is_read)/delete only.
enum NotificationType {
  newLike,
  newMatch,
  newMessage,
  callIncoming,
  callMissed,
  profileView,
  profileVerified,
  subscriptionExpiring,
  subscriptionActive,
  reportUpdate,
  system,
}

NotificationType _typeFromString(String value) => switch (value) {
      'new_like' => NotificationType.newLike,
      'new_match' => NotificationType.newMatch,
      'new_message' => NotificationType.newMessage,
      'call_incoming' => NotificationType.callIncoming,
      'call_missed' => NotificationType.callMissed,
      'profile_view' => NotificationType.profileView,
      'profile_verified' => NotificationType.profileVerified,
      'subscription_expiring' => NotificationType.subscriptionExpiring,
      'subscription_active' => NotificationType.subscriptionActive,
      'report_update' => NotificationType.reportUpdate,
      _ => NotificationType.system,
    };

/// In-app activity feed item. The `data` payload's shape depends on [type] —
/// see migration_004.md "Deep Link Payload" (e.g. `data['conversation_id']`
/// for `newMessage`, `data['match_id']` for `newMatch`).
class AppNotification extends Equatable {
  const AppNotification({
    required this.id,
    required this.type,
    required this.title,
    required this.body,
    required this.createdAt,
    this.actorUserId,
    this.data = const {},
    this.isRead = false,
    this.readAt,
  });

  final String id;
  final NotificationType type;
  final String title;
  final String body;
  final DateTime createdAt;
  final String? actorUserId;
  final Map<String, dynamic> data;
  final bool isRead;
  final DateTime? readAt;

  factory AppNotification.fromJson(Map<String, dynamic> json) =>
      AppNotification(
        id: json['id'] as String,
        type: _typeFromString(json['type'] as String),
        title: json['title'] as String? ?? '',
        body: json['body'] as String? ?? '',
        createdAt: DateTime.parse(json['created_at'] as String),
        actorUserId: json['actor_user_id'] as String?,
        data: (json['data'] as Map<String, dynamic>?) ?? const {},
        isRead: json['is_read'] as bool? ?? false,
        readAt: json['read_at'] == null
            ? null
            : DateTime.parse(json['read_at'] as String),
      );

  @override
  List<Object?> get props => [id, type, isRead];
}
